# Generated by Django 3.2.15 on 2022-08-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Избранное', 'verbose_name_plural': 'Избранное'},
        ),
    ]
